### ISSUE TITLE
Fix issues in README

### ISSUE THREAD

**Issue by sansyrox** [stealthanthrax/kasper_music_player#16]
There might be some issues in the README file, find and fix them by creating a PR

**Comment by Archies11** [comment]
May I work on this?

**Comment by sansyrox** [comment]
Sure @Archies11 👍

**Comment by Archies11** [comment]
What issues are we referring to ?

**Comment by sansyrox** [comment]
Any grammatical/logical mistakes in the readme

**Comment by Kartik2301** [comment]
@opencodebot claim

**Comment by SuneetKumar19** [comment]
@opencodebot claim
