### ISSUE TITLE
Write Tests for the backend

### ISSUE THREAD

**Issue by sansyrox** [stealthanthrax/kasper_music_player#18]
**Is your feature request related to a problem? Please describe.**
Currently, no tests are present for the server.py file.

**Describe the solution you'd like**
Create a test folder and start writing tests for the server

**Additional context**
PyTest library should be used for these

**Comment by Archies11** [comment]
Can I work on this?

**Comment by sansyrox** [comment]
Sure @Archies11 , go ahead 👍

**Comment by Archies11** [comment]
I am not familiar with how i should proceed while solving such issues, are there any links or tutorials that might help me?

**Comment by sansyrox** [comment]
@Archies11 , have a look here https://semaphoreci.com/community/tutorials/testing-python-applications-with-pytest

**Comment by Archies11** [comment]
Ok, will do. Thank you:)

**Comment by sansyrox** [comment]
@Archies11 , any updates?

**Comment by Archies11** [comment]
I did read the article on the link and also some videos on youtube but I couldnt understand the way I should write and what exactly I should code.

**Comment by sansyrox** [comment]
@Archies11 , I can create one test in the repo and maybe then you can follow the format?

**Comment by Archies11** [comment]
Yes sure:)
Thank you.
