### ISSUE TITLE
Remove package-lock.json file from front-end

### ISSUE THREAD

**Issue by sansyrox** [stealthanthrax/kasper_music_player#20]
**Describe the bug**
Remove package-lock.json file from front-end and add it in the gitignore file

**Comment by Archies11** [comment]
May i work on this?

**Comment by sansyrox** [comment]
Sure go ahead 👍

**Comment by Archies11** [comment]
Am i supposed to copy the contents of package-lock to gitignore file or convert git ignore file to a folder and add the package file to it?
