### ISSUE TITLE
Replace the youtube API with web scrapping 

### ISSUE THREAD

**Issue by sansyrox** [stealthanthrax/kasper_music_player#21]
**Is your feature request related to a problem? Please describe.**
Currently, data API is used with the App and since the calls are not completely free it would be sensible to replace the API with scrapping as it is just used to get video ids

**Describe the solution you'd like**
Use some library like beautiful soup to scrape the vid's from youtube

**Additional context**
One of the highest priority issues.

**Comment by SLakhani1** [comment]
I would like to work on this issue.

**Comment by SLakhani1** [comment]
@opencodebot claim

**Comment by sansyrox** [comment]
Sure @SLakhani1 , go ahead 👍

**Comment by sansyrox** [comment]
@SLakhani1 , any updates?

**Comment by SLakhani1** [comment]
I've written the python script that can scrape the results from youtube according to our query but I am facing the problem fitting it into the modules as currently Front-end is not working properly as I've already mentioned in the Zulip chat.

**Comment by sansyrox** [comment]
@SLakhani1 , you just need to generate the vid of the first result based on the search query provided by the user.
Those params are being passed from the front end.
