### ISSUE TITLE
To add a filter in the scrapping script

### ISSUE THREAD

**Issue by sansyrox** [stealthanthrax/kasper_music_player#33]
**Describe the bug**
Currently, the scrapping script scrapes all the youtube content. But we only need the music files like in the data api.

**Expected behavior**
To add a filter that filter outs all the content that is not music. (need to analyse the metadata in the response)

**Additional context**

**Comment by SLakhani1** [comment]
Can I work on this issue?

**Comment by sansyrox** [comment]
Sure @SLakhani1 . Go ahead 👍

**Comment by sansyrox** [comment]
Completed
