### ISSUE TITLE
To extract thumbnail using scrapping script

### ISSUE THREAD

**Issue by sansyrox** [stealthanthrax/kasper_music_player#34]
**Is your feature request related to a problem? Please describe.**
Currently, no cover art is present. 

**Describe the solution you'd like**
To extract thumbnails from youtube using the scraping script.

**Describe alternatives you've considered**
An option is to use data API.

**Additional context**

**Comment by anupm12** [comment]
Can I work on this?

**Comment by sansyrox** [comment]
Sure @anupm12 , go ahead :rocket:

**Comment by sansyrox** [comment]
Any updates @anupm12 ?

**Comment by anupm12** [comment]
@stealthanthrax I'm working on this.
Give me one more day please

**Comment by sansyrox** [comment]
Okay , no worries @anupm12 👍

**Comment by anupm12** [comment]
@stealthanthrax I tried but could not.
I'm no longer working on this issue.

**Comment by sansyrox** [comment]
@anupm12 , if you are facing any specific issues, maybe I can suggest an alternative.

**Comment by anupm12** [comment]
I'll try it again today.

**Comment by sansyrox** [comment]
If it's any help , try rendering images on the client side instead of the server side using this library https://www.npmjs.com/package/album-art
